// GENERATED by scripts/build-registry.mjs — do not edit by hand.
// Maps demo name → component; DemoBlock renders from this and fetches
// the matching /demos/<name>.txt for the code view.

import AccordionDemo from "./accordion-demo";
import ActivityFeedDemo from "./activity-feed-demo";
import AlertDemo from "./alert-demo";
import AlertDialogDemo from "./alert-dialog-demo";
import AspectRatioDemo from "./aspect-ratio-demo";
import AttachmentDemo from "./attachment-demo";
import AvatarDemo from "./avatar-demo";
import BadgeDemo from "./badge-demo";
import BreadcrumbDemo from "./breadcrumb-demo";
import BubbleDemo from "./bubble-demo";
import ButtonDemo from "./button-demo";
import ButtonGroupDemo from "./button-group-demo";
import ButtonLoading from "./button-loading";
import ButtonVariants from "./button-variants";
import CalendarDemo from "./calendar-demo";
import CardDemo from "./card-demo";
import CarouselDemo from "./carousel-demo";
import ChartDemo from "./chart-demo";
import CheckboxDemo from "./checkbox-demo";
import CodeSnippetDemo from "./code-snippet-demo";
import CollapsibleDemo from "./collapsible-demo";
import ColorPickerDemo from "./color-picker-demo";
import ComboboxDemo from "./combobox-demo";
import CommandDemo from "./command-demo";
import ContextMenuDemo from "./context-menu-demo";
import DataTableDemo from "./data-table-demo";
import DatePickerDemo from "./date-picker-demo";
import DialogDemo from "./dialog-demo";
import DrawerDemo from "./drawer-demo";
import DropdownMenuDemo from "./dropdown-menu-demo";
import EmptyDemo from "./empty-demo";
import FeaturedIconDemo from "./featured-icon-demo";
import FieldDemo from "./field-demo";
import FileUploaderDemo from "./file-uploader-demo";
import FilterBarDemo from "./filter-bar-demo";
import HoverCardDemo from "./hover-card-demo";
import InputDemo from "./input-demo";
import InputGroupDemo from "./input-group-demo";
import InputOtpDemo from "./input-otp-demo";
import ItemDemo from "./item-demo";
import KbdDemo from "./kbd-demo";
import LabelDemo from "./label-demo";
import MarkerDemo from "./marker-demo";
import MenubarDemo from "./menubar-demo";
import MessageDemo from "./message-demo";
import MessageScrollerDemo from "./message-scroller-demo";
import MetricDemo from "./metric-demo";
import MultiSelectDemo from "./multi-select-demo";
import NativeSelectDemo from "./native-select-demo";
import NavigationMenuDemo from "./navigation-menu-demo";
import NotificationsDemo from "./notifications-demo";
import PageHeaderDemo from "./page-header-demo";
import PaginationDemo from "./pagination-demo";
import PopoverDemo from "./popover-demo";
import ProgressDemo from "./progress-demo";
import ProgressStepsDemo from "./progress-steps-demo";
import QrCodeDemo from "./qr-code-demo";
import RadioGroupDemo from "./radio-group-demo";
import RatingDemo from "./rating-demo";
import ResizableDemo from "./resizable-demo";
import RichTextEditorDemo from "./rich-text-editor-demo";
import ScrollAreaDemo from "./scroll-area-demo";
import SectionHeaderDemo from "./section-header-demo";
import SelectDemo from "./select-demo";
import SeparatorDemo from "./separator-demo";
import SheetDemo from "./sheet-demo";
import SidebarDemo from "./sidebar-demo";
import SkeletonDemo from "./skeleton-demo";
import SliderDemo from "./slider-demo";
import SocialButtonsDemo from "./social-buttons-demo";
import SpinnerDemo from "./spinner-demo";
import SwitchDemo from "./switch-demo";
import TableDemo from "./table-demo";
import TabsDemo from "./tabs-demo";
import TagInputDemo from "./tag-input-demo";
import TextareaDemo from "./textarea-demo";
import ToastDemo from "./toast-demo";
import ToggleDemo from "./toggle-demo";
import ToggleGroupDemo from "./toggle-group-demo";
import TooltipDemo from "./tooltip-demo";
import TreeViewDemo from "./tree-view-demo";
import TypographyComponentDemo from "./typography-component-demo";
import VideoPlayerDemo from "./video-player-demo";

export const DEMOS: Record<string, React.ComponentType> = {
  "accordion-demo": AccordionDemo,
  "activity-feed-demo": ActivityFeedDemo,
  "alert-demo": AlertDemo,
  "alert-dialog-demo": AlertDialogDemo,
  "aspect-ratio-demo": AspectRatioDemo,
  "attachment-demo": AttachmentDemo,
  "avatar-demo": AvatarDemo,
  "badge-demo": BadgeDemo,
  "breadcrumb-demo": BreadcrumbDemo,
  "bubble-demo": BubbleDemo,
  "button-demo": ButtonDemo,
  "button-group-demo": ButtonGroupDemo,
  "button-loading": ButtonLoading,
  "button-variants": ButtonVariants,
  "calendar-demo": CalendarDemo,
  "card-demo": CardDemo,
  "carousel-demo": CarouselDemo,
  "chart-demo": ChartDemo,
  "checkbox-demo": CheckboxDemo,
  "code-snippet-demo": CodeSnippetDemo,
  "collapsible-demo": CollapsibleDemo,
  "color-picker-demo": ColorPickerDemo,
  "combobox-demo": ComboboxDemo,
  "command-demo": CommandDemo,
  "context-menu-demo": ContextMenuDemo,
  "data-table-demo": DataTableDemo,
  "date-picker-demo": DatePickerDemo,
  "dialog-demo": DialogDemo,
  "drawer-demo": DrawerDemo,
  "dropdown-menu-demo": DropdownMenuDemo,
  "empty-demo": EmptyDemo,
  "featured-icon-demo": FeaturedIconDemo,
  "field-demo": FieldDemo,
  "file-uploader-demo": FileUploaderDemo,
  "filter-bar-demo": FilterBarDemo,
  "hover-card-demo": HoverCardDemo,
  "input-demo": InputDemo,
  "input-group-demo": InputGroupDemo,
  "input-otp-demo": InputOtpDemo,
  "item-demo": ItemDemo,
  "kbd-demo": KbdDemo,
  "label-demo": LabelDemo,
  "marker-demo": MarkerDemo,
  "menubar-demo": MenubarDemo,
  "message-demo": MessageDemo,
  "message-scroller-demo": MessageScrollerDemo,
  "metric-demo": MetricDemo,
  "multi-select-demo": MultiSelectDemo,
  "native-select-demo": NativeSelectDemo,
  "navigation-menu-demo": NavigationMenuDemo,
  "notifications-demo": NotificationsDemo,
  "page-header-demo": PageHeaderDemo,
  "pagination-demo": PaginationDemo,
  "popover-demo": PopoverDemo,
  "progress-demo": ProgressDemo,
  "progress-steps-demo": ProgressStepsDemo,
  "qr-code-demo": QrCodeDemo,
  "radio-group-demo": RadioGroupDemo,
  "rating-demo": RatingDemo,
  "resizable-demo": ResizableDemo,
  "rich-text-editor-demo": RichTextEditorDemo,
  "scroll-area-demo": ScrollAreaDemo,
  "section-header-demo": SectionHeaderDemo,
  "select-demo": SelectDemo,
  "separator-demo": SeparatorDemo,
  "sheet-demo": SheetDemo,
  "sidebar-demo": SidebarDemo,
  "skeleton-demo": SkeletonDemo,
  "slider-demo": SliderDemo,
  "social-buttons-demo": SocialButtonsDemo,
  "spinner-demo": SpinnerDemo,
  "switch-demo": SwitchDemo,
  "table-demo": TableDemo,
  "tabs-demo": TabsDemo,
  "tag-input-demo": TagInputDemo,
  "textarea-demo": TextareaDemo,
  "toast-demo": ToastDemo,
  "toggle-demo": ToggleDemo,
  "toggle-group-demo": ToggleGroupDemo,
  "tooltip-demo": TooltipDemo,
  "tree-view-demo": TreeViewDemo,
  "typography-component-demo": TypographyComponentDemo,
  "video-player-demo": VideoPlayerDemo,
};
